// AUTO-GENERATED by scripts/list-mothers-day-photos.mjs — do not edit by hand.
// Re-run `npm run prebuild` (or any `npm run build`) to regenerate after
// adding or removing files in public/mothers-day/.

export const HERO_PHOTO: string | null = "/mothers-day/042C2D9C-46E4-4DD0-9B09-DBD490A394A2_1_105_c.jpeg";

export const COLLAGE_PHOTOS: readonly string[] = [
  "/mothers-day/0B7930DF-F2A0-4F93-B33C-A2879C9127A4_1_105_c.jpeg",
  "/mothers-day/235DEBBE-B57B-479F-AF7B-71FF6FD955A0_1_105_c.jpeg",
  "/mothers-day/29534259-40DE-4282-8FAC-9EE9DA2A0B38_1_105_c.jpeg",
  "/mothers-day/2C2F4CF5-3AFB-46A1-9E21-CD2A1C875F5B_1_105_c.jpeg",
  "/mothers-day/3291AA37-C107-462E-BB3B-982B42CB9C54_1_105_c.jpeg",
  "/mothers-day/33B2A9CF-E1C7-470F-AD99-BA8262625D00_1_105_c.jpeg",
  "/mothers-day/409978F7-D7EB-48B1-B959-4D41CC3FE5FF_1_105_c.jpeg",
  "/mothers-day/44F8AE32-54D8-4413-BE22-0EB180263BF3_1_105_c.jpeg",
  "/mothers-day/542C338D-0A12-4F8C-AEF6-FB7AB3695BA4_1_105_c.jpeg",
  "/mothers-day/5568CAB3-B9C0-445C-9C3C-646EDA6057A6_1_105_c.jpeg",
  "/mothers-day/5B110C00-C040-487A-8CD1-6C0634D30079_1_105_c.jpeg",
  "/mothers-day/72EE5686-E6A4-408D-AD40-EC3B4A56851E_1_105_c.jpeg",
  "/mothers-day/764C13F2-B0A4-4152-ACC3-E044A8B27EF0_1_105_c.jpeg",
  "/mothers-day/7D35242E-90A6-4C3B-9D1D-6203CFC67A5C_1_105_c.jpeg",
  "/mothers-day/822CD57B-57F3-4624-8B66-543B57FAAA11_1_105_c.jpeg",
  "/mothers-day/87AC491E-243F-483B-95F5-C400839D086A_1_105_c.jpeg",
  "/mothers-day/8AA83345-4E8E-4DFB-83EE-2D2736CA562C_1_105_c.jpeg",
  "/mothers-day/8C6010B7-C030-46F4-9E17-6390FF30C7B7_1_105_c.jpeg",
  "/mothers-day/92AFAE5D-62F6-4BE5-BFDB-E98C6F035C80_1_105_c.jpeg",
  "/mothers-day/9B7BE3B3-FF32-4C5F-8988-ECD3441EEE45_1_105_c.jpeg",
  "/mothers-day/9F0AD3AF-CF02-44DD-833A-6FEC8C3DFFFD_1_105_c.jpeg",
  "/mothers-day/A5471951-5A56-441C-9ADF-B13FBBA296A7_1_105_c.jpeg",
  "/mothers-day/B51FB65E-8845-497B-90D3-6B08D0563DF7_1_105_c.jpeg",
  "/mothers-day/C109A5D2-9577-4758-A902-E99E96D56646_1_105_c.jpeg",
  "/mothers-day/C726634B-7CB8-46E6-8442-4B3A1BFACE0A_1_105_c.jpeg",
  "/mothers-day/D3BA94B6-8F51-46DE-BCE8-64B325DCEFC8_1_105_c.jpeg",
  "/mothers-day/E075DB67-BF19-4AB8-96FE-5BB7197761F5_1_105_c.jpeg",
  "/mothers-day/E7C501DD-5100-43AC-8CC8-CC57081F1FA4_1_105_c.jpeg",
  "/mothers-day/ED28B6A2-DE6C-4C4B-AD24-9B55C3D66F86_1_105_c.jpeg",
  "/mothers-day/F014FE0D-40D4-48FA-81E7-7F8AB8021395_1_105_c.jpeg",
  "/mothers-day/F6DF3774-9FC0-4B70-B24E-C928790A86EB_1_105_c.jpeg",
  "/mothers-day/F8364FCE-06EB-4FB1-9359-5A5D7DC2DD5B_1_105_c.jpeg",
  "/mothers-day/FB10423A-64F2-4D35-AADF-B831CB0770F6_1_105_c.jpeg",
  "/mothers-day/FCB1F011-97AB-4574-9CA7-04293008FAAE_1_105_c.jpeg"
] as const;
